---
title: "Indian Premier League (IPL) data analysis"
subtitle: 'STAT585 Final Project'
date: "`r format(Sys.time(), '%d %B %Y')`"
author: "Ashish Jain"
output: pdf_document
---

##Abstract
Cricket is one of the most popular and played sports in India. There are three standard types of cricket matches, Five-day match (Test Match), 50 overs match (One day match), and Twenty overs match (T20). Although all formats are quite popular but during the last decade, the popularity of the T20 matches has increased exponentially. The main reason for the popularity of T20 matches is more action in short time. The introduction of various T20 tournaments has also added to its popularity. Indian Premier League (IPL) is the biggest event among all the T20 tournaments across the globe. It is an annual tournament and consists of two stages. In the first or the league stage, each team plays against the other team twice. In the second stage, the top four teams after the league stage compete for the title. We are going to use the IPL data from the year 2008 to 2016. The raw data has been downloaded from [Cricsheet website](http://cricsheet.org/downloads/). The raw data consists ball by ball details of every match individually for every match (577 files). The CSV file also has a summary of the match. For carrying out the analysis we have divided this project into two parts. In the first part, we will clean and format (tidy form) the data so that it can be used for the next part (visualization and analysis). In the next part, we will develop a shiny application in which the data can be analyzed by plotting and changing various parameters including year, team, and player.

The GitHub repository which I am using for this project is https://github.com/ashishjain1988/STAT585/
